on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2

    - name: Use NodeJS 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Build CSS
      run: |
        npm install
        npm run buildcss
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.bytesfest.web.id
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: ./app/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
